name: native_device_orientation
description: A Flutter plugin for reading device's native orientation, either from UI orientation or from sensors
version: 1.0.2
homepage: https://github.com/rmtmckenzie/flutter_native_device_orientation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: com.github.rmtmckenzie.native_device_orientation
        pluginClass: NativeDeviceOrientationPlugin
      ios:
        pluginClass: NativeDeviceOrientationPlugin
